services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    platform: ${MONGO_PLATFORM:-linux/amd64}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  
  import-data:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: import-data
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://admin:password@mongodb:27017/storesDB?authSource=admin"
    command: ["node", "import.js"]
    restart: "no"  

  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: node-BE
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://admin:password@mongodb:27017/storesDB?authSource=admin"

  
  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    container_name: nginx-FE
    ports:
      - "5001:80" 
    depends_on:
      - backend  
    

volumes:
  mongo_data:
